config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get  '/signup',   to: 'users#new'
  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  # get '/edit-basic-info/:id', to: 'users#edit_basic_info', as: :basic_info  勤怠Aでは使わない
  # patch 'update-basic-info',  to: 'users#update_basic_info'  勤怠Aでは使わない
  
  #勤怠編集画面
  get 'users/:id/attendances/:date/edit', to: 'attendances#edit', as: :edit_attendances
  patch 'users/:id/attendances/:date/update', to: 'attendances#update', as: :update_attendances
  
  #残業申請
  post '/overwork_request/:id', to: 'users#overwork_request', as: :overwork_request
  patch '/users/:id/attendances/:attendance_id/update_overwork_request',  to: 'attendances#update_overwork_request', as: :update_overwork_request
  
  #残業申請受け取り、承認
  post '/overwork_permit/:id', to: 'users#overwork_permit', as: :overwork_permit_modal
  patch '/users/:id/attendances/overwork_permit', to: 'attendances#overwork_permit', as: :overwork_permit
  
  #１ヶ月分の勤怠申請、承認
  post '/month_request_modal/:id', to: 'users#month_request_modal', as: :month_request_modal
  patch '/users/:id/attendances/month_request', to: 'attendances#month_request', as: :month_request
  get  'confirmation/:id/:date', to: 'users#confirmation', as: :confirmation
  
   # 勤怠変更申請、承認
  post '/edit_request/:id/:date', to: 'users#edit_request', as: :edit_request_modal
  patch '/users/:id/attendances/edit_request', to: 'attendances#edit_request', as: :edit_request
  
  #勤怠ログ
  get '/change_log/:id', to: 'attendances#change_log', as: :change_log
  
  get '/worktime_logs/search', to: 'attendances#worktime_logs'
  
  #CSV出力
  post '/csv_dl/:id', to: 'users#csv_dl', as: :csv_dl
  post '/csv_import', to: 'users#csv_import', as: :csv_import
  
  
  
  #出勤中社員
  get 'working_now',  to: 'users#working_now', as: :working_now
  
  resources :users do
    collection { post :import }
  resources :attendances, only: :create
  end
  
  resources :basepoints do
    member do
      get 'edit_base'
      patch 'update_base'
    end
  end
  
  resources :monthrequests,  only: [:create]
  
end

app/models/user.rb
class User < ApplicationRecord
  has_many :attendances, dependent: :destroy
  before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  validates :affiliation, length: { in: 2..50 }, allow_blank: true
  validates :basic_work_time, presence: true
  validates :designated_work_start_time, presence: true
  validates :designated_work_end_time, presence: true
  
  validates :uid, presence: true, uniqueness: true
  validates :employee_number, presence: true, uniqueness: true, numericality: { only_integer: true }
  
  has_many :attendances, dependent: :destroy
  has_many :monthrequests, dependent: :destroy
  
  # csv import class
  def self.import(file)
    begin
      CSV.foreach(file.path, headers: true) do |row|
        # IDが見つかれば、レコードを呼び出し、見つかれなければ、新しく作成
        @user = find_by(id: row["id"]) || new
        # CSVからデータを取得し、設定する
        @user.attributes = row.to_hash.slice(*updatable_attributes)
        # 保存する
        @user.save
      end
      @user.errors.any? ? msg = "#{@user.errors.count}個のエラー" : msg = "登録完了"
    rescue CSV::MalformedCSVError
      msg = "文字コードUTF-8で登録してください。"
    rescue ActiveRecord::RecordNotUnique
      msg = "重複しているデータがあります。"
    rescue => e
      msg = "#{e.class}"
    end
    
  end
  
  # 更新を許可するカラムを定義
  def self.updatable_attributes
    ["name", "email", "affiliation", "employee_number", "uid", "basic_work_time",
    "designated_work_start_time", "designated_work_end_time", "superior", "admin", "password"]
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update, :show, :destroy]
  before_action :correct_user,   only: [:edit, :update,:show, :csv_dl]
  before_action :admin_user,     only: [:destroy, :edit_basic_info, :update_basic_info,:index, :working_now, :csv_import]
  before_action :except_admin,    only: [:show, :csv_dl, :overwork_request, :overwork_permit, :month_request_modal, :edit_request, :confirmation]

  def index
    @users = User.paginate(page: params[:page]).where.not(admin: true) #admin: trueのユーザーは取得しない。
    
  end
  
  def new
    @user = User.new
    make_new_user
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "ユーザーの新規作成に成功しました。"
      redirect_to @user
    else
      make_new_user
      render 'new'
    end
  end
  
  def edit
    @user = User.find(params[:id])
    @first_day = first_day(params[:date])
    @last_day = @first_day.end_of_month
    @dates = user_attendances_month_date
  end

 def show
    @user = User.find(params[:id])
    @first_day = first_day(params[:first_day]).beginning_of_month
    @last_day = @first_day.end_of_month # @first_dayにend_of_monthを記述することで、末日を取得できる。
    (@first_day..@last_day).each do |day| #ブロック変数のdayオブジェクトは、Dateクラスから取得した日付データ。
      unless @user.attendances.any? {|attendance| attendance.worked_on == day} #@userに紐付いた、当月の初日から末日までのattendancesテーブルのレコードがあるか確認。
        record = @user.attendances.build(worked_on: day) #無い場合該当する日付をworked_onに代入。
        record.save #代入後保存
      end
    end
    @dates = user_attendances_month_date
    @worked_sum = @dates.where.not(started_at: nil).count
    
    @monthrequest = @user.monthrequests
    .where(req_date: @first_day)
    .where(user_id: params[:id])
    .order(req_date: :desc).limit(1)
    
    # 承認の確認していない項目について
    @boss_notice = Monthrequest.where('boss_id = ?', params[:id]).where.not(month_approval: ['承認','否認'])
    
    # 勤怠変更申請の確認していない項目について(全期間調べる必要あり)
    @time_change_notice = Attendance.where('conf_change = ?', params[:id])
    .where.not(edit_request_permit: ['承認','否認'])
    .order('worked_on')
    
    # 残業申請表示に必要
    @overtime_notice = Attendance.where('overwork_superior = ?', params[:id])
    .where.not(work_request_permit: ['承認','否認'])
    .order('worked_on')
    
    @all_user = User.where(superior: true).where.not(id: params[:id])
 end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "ユーザー情報を更新しました。"
      redirect_to users_path
    else
      render 'edit'
    end
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "削除しました。"
    redirect_to users_url
  end
  
  def csv_dl
    user = User.find(params[:id])
    first_day = first_day(params[:first_day]).beginning_of_month
    last_day = first_day.end_of_month
    @attendances = user.attendances.where('worked_on >= ? and worked_on <= ?', first_day, last_day).order('worked_on')
    
    respond_to do |format|
      # format.html do
      #     #html用の処理を書く
      # end 
      format.csv do
          send_data render_to_string, filename: "attendance.csv", type: :csv
      end
    end
  end
  
  def csv_import
    if params[:csv_file].blank?
      flash[:danger] = "読み込むCSVを選択してください。"
      redirect_to users_url
    elsif File.extname(params[:csv_file].original_filename) != ".csv"
      flash[:danger] = "csvファイルのみ読み込み可能です。"
      redirect_to users_url
    else
      # import_data
      # registered_count = import_data
      # flash[:success] = "#{registered_count}件登録しました。"
      msg = User.import(params[:csv_file])
      msg == "登録完了" ? flash[:success] = msg : flash[:danger] = msg
      redirect_to users_url
      # @users_data = User.all
      # render "index"
    end
  end
  
   #残業申請モーダル表示
  def overwork_request
    @attendance_id = params[:id] #idを取得し@attendance_idに代入
    @user = Attendance.find(params[:id]).user #userレコードからAttendanceモデルのidを取得し、@userに代入
    @first_day = first_day(params[:first_day]).beginning_of_month #first_day(date)の月初を@first_dayに代入
    @dates = @user.attendances.find(@attendance_id)
    @all_user = User.where(superior: true).where.not(id: @user.id) #superior: trueを全て取得。idが@user.id以外のユーザーを全て取得
  end
  
  #残業申請承認
  def overwork_permit #overtime_permit_modal（モーダル表示アクション）
  @user = User.find(params[:id]) #Userモデルからidを取得し、@userに代入
  #↓ ? 「プレースホルダ」値が入るまで（仮）一時保存、idが入ったらカラムに置き換えられる
  #↓第２引数がカラムに入った第１引数に当てはまるAttendanceモデルのレコードを全て取得し、@work_requestsに代入
  @work_requests = Attendance.where('overwork_superior = ?', params[:id])
  .where.not(work_request_permit: ['承認','否認'])#work_request_permitが'承認','否認'以外のAttendanceを全て取得
    .order('user_id').order('worked_on') #orderメソッドで取得データを並び替え
  end
  
  #勤怠変更申請、承認
  def edit_request
    @edit_requests = Attendance.where('conf_change = ?', params[:id])
    .where.not(edit_request_permit: ['承認','否認'])
    .order('user_id').order('worked_on')
    @user = User.find(params[:id])
  end
  
  #１ヶ月分の勤怠申請、承認
  def month_request_modal
     @user = User.find(params[:id])
     @month_requests = Monthrequest.where('boss_id = ?', params[:id])
    .where.not(month_approval: ['承認','否認'])
    .order('user_id').order('req_date')
  end
  
  def confirmation #残業申請（勤怠確認）
  @user = User.find(params[:id])
    @first_day = first_day(params[:date]).beginning_of_month
    @last_day = @first_day.end_of_month
    (@first_day..@last_day).each do |day|
      unless @user.attendances.any? {|attendance| attendance.worked_on == day}
        record = @user.attendances.build(worked_on: day)
        record.save
      end
    end
    @dates = user_attendances_month_date
    @worked_sum = @dates.where.not(started_at: nil).count
    # 月の申請
    @monthrequest = @user.monthrequests
    .where(req_date: @first_day)
    .where(user_id: params[:id])
    .order(req_date: :desc).limit(1)
  end
  
  def update_basic_info
  @user = User.find(params[:id])
   if @user.update_attributes(basic_info_params)
    flash[:success] = "基本情報を更新しました。"
    redirect_to @user   
   else
    render 'edit_basic_info'
   end
  end
  
  
  def edit_basic_info
    @user = User.find(params[:id])
    @first_day = Date.parse(params[:date])
    @last_day = @first_day.end_of_month
    @dates = @user.attendances.where('worked_on >= ? and worked_on <= ?', @first_day, @last_day).order('worked_on')
  end
  
  def working_now
    @users = User.all
  end


private
  def user_params
    params.require(:user).permit(:name, :email, :affiliation,:employee_number,:uid, :password, :password_confirmation,:basic_work_time,:designated_work_start_time,:work_finish_time)
  end

  def basic_info_params
    params.require(:user).permit(:basic_time, :designated_work_start_time)
  end
  
    # beforeアクション

    # ログイン済みユーザーか確認
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "ログインしてください。"
        redirect_to login_url
      end
    end

    # 正しいユーザーかどうか確認
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user) or current_user.admin?
    end
    
    def superior_user
      redirect_to(root_url) unless current_user.superior?
    end
    
    
    # 管理者かどうか確認
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
    
    def except_admin
     redirect_to users_url if current_user.admin?
    end
end

app/helpers/users_helper.rb
module UsersHelper
    # 基本時間などの値を、指定の書式にフォーマットして返す
  def format_basic_work_time(datetime)
    format("%.2f", ((datetime.hour * 60) + datetime.min)/60.0)
  end
  
  # User table idから名前入れる
  def u_name(f_id)
    if !f_id.blank?
      User.find(f_id).name
    end
  end
  
  
end

app/views/users/_edit_request.html.erb
<div class="modal-dialog modal-lg">
	<div class="modal-content">
		<div class="modal-body">
			<button type="button" class="close" data-dismiss="modal"><span>×</span></button>

		<%= form_for(@user, url: "/users/#{@user.id}/attendances/edit_request", method: :patch) do |f| %>
		<% header_user_id = nil %>
		<% @edit_requests.each do |req| %>
      <% if header_user_id != req.user_id %>
      <% header_user_id = req.user_id %>
      
			<table class = "table-bordered table-striped table-condensed">
			  <h4 class="center">【<%= User.find(req.user_id).name %>からの勤怠変更申請】</h4>
        <thead>
          <tr>
            <th rowspan = "3">日付</th>
            <th rowspan = "3">曜日</th>
            <th colspan = "4">変更前</th>
            <th colspan = "4">変更後</th>
            <th rowspan = "3">備考</th>
            <th rowspan = "3">指示者確認㊞</th>
            <th rowspan = "3">変更</th>
            <th rowspan = "3">勤怠を確認</th>
          </tr>
          <tr>
            <th colspan = "2">出社</th>
            <th colspan = "2">退社</th>
            <th colspan = "2">出社</th>
            <th colspan = "2">退社</th>
          </tr>
          <tr>
            <th>時</th>
            <th>分</th>
            <th>時</th>
            <th>分</th>
            <th>時</th>
            <th>分</th>
            <th>時</th>
            <th>分</th>
          </tr>
        </thead>
        <% end %>
        <tbody>
          <% unless (req.origin_start == req.started_at && req.origin_fin == req.finished_at) %>
              <%= fields_for "attendances[]", req do |af| %>
                <tr>
                  <td><%= req.worked_on.to_s(:date) %></td>
                  <td><%= %w{日 月 火 水 木 金 土}[req.worked_on.wday] %></td>
                  <td><%= req.origin_start.to_s(:hour) if req.origin_start.present? %></td>
                  <td><%= req.origin_start.to_s(:min) if req.origin_start.present? %></td>
                  <td><%= req.origin_fin.to_s(:hour) if req.origin_fin.present? %></td>
                  <td><%= req.origin_fin.to_s(:min) if req.origin_fin.present? %></td>
                  <td><%= req.started_at.to_s(:hour) if req.started_at.present? %></td>
                  <td><%= req.started_at.to_s(:min) if req.started_at.present? %></td>
                  <td><%= req.finished_at.to_s(:hour) if req.finished_at.present? %></td>
                  <td><%= req.finished_at.to_s(:min) if req.finished_at.present? %></td>
                  
                  <td><%= req.note %></td>
                  <td>
                  <%= af.select :edit_request_permit, 
                  {"なし" => "なし", "申請中" => "申請中", "承認" => "承認", "否認" => "否認"},
                  {}, class: "form-control" %>
                  </td>
                  <td style="width:40px;"><%= af.check_box 'change', {:checked => false}, true, false %></td>
                  <td><%= link_to '確認', "/confirmation//#{req.user_id}/#{req.worked_on}", target: :_blank, class: "btn btn-primary" %></td>
                </tr>
              <% end %>
            <% end %>
          <% end %>
        </tbody>
      </table>
      
    <%= f.submit "更新", class: "btn btn-primary btn-block modal-button-space" %>
    <% end %>
		</div>
	</div>
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', object: @user %>

  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>

  <%= f.label :affiliation %>
  <%= f.text_field :affiliation, class: 'form-control' %>

  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>
  
  <% if @ini_uid %>
    <%= f.hidden_field :uid, value: @ini_uid %>
    <%= f.hidden_field :employee_number, value: @ini_employee_number %>
  <% end %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/users/_month_request_modal.html.erb
	<div class="modal-dialog modal-lg">
		<div class="modal-content">
			<div class="modal-body">
				<button type="button" class="close" data-dismiss="modal"><span>×</span></button>
  
			<%= form_for(@user, url: "/users/#{@user.id}/attendances/month_request", method: :patch) do |f| %>
			<% header_user_id = nil %>
			<% @month_requests.each do |month_request| %>
			
        <% if header_user_id != month_request.user_id %>
        <% header_user_id = month_request.user_id %>
				<table class = "table-bordered table-striped table-condensed">
				  <h4 class="center">【<%= User.find(month_request.user_id).name %>からの１ヵ月分勤怠申請】</h4>
          <thead>
            <tr>
              <th>月</th>
              <th>指示者確認㊞</th>
              <th>変更</th>
              <th>勤怠を確認</th>
            </tr>
          </thead>
        
        <% end %>
          <tbody>
            <% unless month_request.month_approval == "承認" %>
                <%= fields_for "month_requests[]", month_request do |af| %>
                  <tr>
                    <td><%= month_request.req_date.strftime("%-m") %>月</td>
                    <td>
                    <%= af.select :month_approval, 
                    {"なし" => "なし", "申請中" => "申請中", "承認" => "承認", "否認" => "否認"},
                    {}, class: "form-control" %>
                    </td>
                    <td style="width:40px;"><%= af.check_box 'change', {:checked => false}, true, false %></td>
                    <td><%= link_to '確認', "/confirmation/#{month_request.user_id}/#{month_request.req_date}", target: :_blank, class: "btn btn-primary" %></td>
                  </tr>
                <% end %>
              <% end %>
            <% end %>
          </tbody>
        </table>
      <%= f.submit "更新", class: "btn btn-primary btn-block modal-button-space" %>
      <% end %>
			</div>
		</div>
	</div>
</div>

app/views/users/edit_request.js.erb
$("#user-modal").html("<%= escape_javascript(render 'edit_request') %>") ;
$("#user-modal").modal("show") ;

app/views/users/index.html.erb
<% provide(:title, 'ユーザー一覧') %>

 <h1>ユーザー一覧</h1>

<%= will_paginate @users, :previous_label => '&lt 前へ', :next_label => '次へ &gt' %>

<%= form_tag csv_import_path, method: :post, multipart: true do |f| %>
<div class="row">
  <div class="col-md-6">
    <div class="input-group">
        <label class="input-group-btn">
            <span class="btn btn-primary">
                ファイルを選択<%= file_field_tag 'csv_file', id: "file_input", style: "display: none;" %>
            </span>
        </label>
        <input type="text" class="form-control" readonly="">
    </div>
    <button type="submit" class="btn btn-primary", style= "margin: 10px 0;">CSVをインポート</button>
  </div>
</div>
<% end %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate @users, :previous_label => '&lt 前へ', :next_label => '次へ &gt' %>

<script type="text/javascript">
  $(document).on('change', ':file', function() {
    var input = $(this),
    numFiles = input.get(0).files ? input.get(0).files.length : 1,
    label = input.val().replace(/\\/g, '/').replace(/.*\//, '');
    input.parent().parent().next(':text').val(label);
  });
</script>

app/views/users/show.html.erb
<% provide(:title, '勤怠表示') %>
<div>
  <table class = "table-bordered table-condensed">
    <tr>
      <td>
        <%= link_to "←", user_path(params: {id: @user.id, first_day: @first_day.prev_month }),
                         class: "btn btn-xs btn-primary" %>
        &emsp;<%= @first_day.to_s(:year_month) %>　時間管理表&emsp;
        <%= link_to "→", user_path(params: {id: @user.id, first_day: @first_day.next_month }),
                         class: "btn btn-xs btn-primary" %>
      </td>
      <td>
        <br>指定勤務開始時間　<%= format_basic_work_time(@user.designated_work_start_time) %></br>
        <br>指定勤務終了時間　<%= format_basic_work_time(@user.designated_work_end_time) %></br>
      </td>
      <td colspan = "3">基本時間　<%= format_basic_work_time(@user.basic_work_time) %></td>
      <td>初日　<%= @first_day.to_s(:date) %></td>
    </tr>
    <tr>
      <td>所属：<%= @user.affiliation.present? ? @user.affiliation : "未設定" %></td>
      <td>氏名：<%= @user.name %></td>
      <td>コード</td>
      <td><%= @user.employee_number%></td>
      <td>出勤日数：<%= @worked_sum %>日</td>
      <td>締日　<%= @last_day.to_s(:date) %></td>
    </tr>
  </table>
  
  <% if !@boss_notice.blank? %>
  <p><%= link_to '【所属長承認申請のお知らせ】',"/month_request_modal/#{@user.id}", remote: true ,method: :post %>
  <span class="notice-count"><%="#{@boss_notice.count}件"%>
      </span></p>
  <% elsif @user.superior %>
    <p>【残業申請のお知らせ】</p>
  <% end %>
  
  <% if !@time_change_notice.blank? %>
  <p><%= link_to '【勤怠変更申請のお知らせ】',"/edit_request/#{@user.id}/#{@first_day}", remote: true,method: :post %>
  <span class="notice-count"><%="#{@time_change_notice.count}件"%>
      </span></p>
  <% elsif @user.superior %>
    <p>【勤怠変更申請のお知らせ】</p>
  <% end %>
  
  <% if !@overtime_notice.blank? %>
  <p><%= link_to '【残業申請のお知らせ】',"/overwork_permit/#{@user.id}", remote: true,method: :post %>
  <span class="notice-count"><%="#{@overtime_notice.count}件"%>
      </span></p>
  <% elsif @user.superior %>
    <p>【残業申請のお知らせ】</p>
  <% end %>

  <%= link_to "勤怠を編集", edit_attendances_path(@user, @first_day), class: "btn btn-primary" %>
  <%= link_to "勤怠ログ", change_log_path(@user), class: "btn btn-primary" %>
  <%= link_to "CSV出力", csv_dl_path(format: :csv), class: "btn btn-primary", method: :post %>

  <table class = "table-bordered  table-condensed table-striped">
    
    <thead>
      <tr> <!--rowspan:縦結合、colspan：横結合-->
        <th rowspan = "3">残業申請</th>
        <th rowspan = "3">日付</th>
        <th rowspan = "3">曜日</th>
        <th colspan = "8">実績</th>
        <th colspan = "5">所定外勤務</th>
      </tr>
      <tr>
        <th colspan = "3">出社</th>
        <th colspan = "3">退社</th>
        <th rowspan = "2">在社時間</th>
        <th rowspan = "2">備考</th>
        <th colspan = "2">終了予定時間</th>
        <th rowspan = "2">時間外時間</th>
        <th rowspan = "2">業務処理内容</th>
        <th rowspan = "2">指示者確認印</th>
      </tr>
      <tr>
        <th>時</th>
        <th>分</th>
        <th></th>
        <th>時</th>
        <th>分</th>
        <th></th>
        <th>時</th>
        <th>分</th>
      </tr>
    </thead>
    
    <tbody>
      <% @dates.each do |day| %>
      <% css_class = case %w{日 月 火 水 木 金 土}[day.worked_on.wday]
    when '土'
      'text-primary'
    when '日'
      'text-danger'
    end
  %>
        <tr>
          <td>
            <%= link_to '残業申請', "/overwork_request/#{day.id}", remote: true, class: "btn btn-primary", method: :post %>
          </td>
          
        
          <td><%= day.worked_on.to_s(:date) %></td>
          <td class="<%= css_class %>"><%= %w{日 月 火 水 木 金 土}[day.worked_on.wday] %></td> 
          <td><%= day.started_at.to_s(:hour) if day.started_at.present? %></td>
          <td><%= day.started_at.floor_to(15.minutes).to_s(:min) if day.started_at.present? %></td> <!--.floor_to(15.minutes)(15.minutes)15分刻みで切り捨て-->
          <td>
            <% if day.worked_on == Date.today && day.started_at.nil? %>
              <%= button_to "出社", user_attendances_path(@user), class: "btn btn-xs btn-primary" %>
            <% end %>
          </td>
          <td><%= day.finished_at.to_s(:hour) if day.finished_at.present? %></td>
          <td><%= day.finished_at.floor_to(15.minutes).to_s(:min) if day.finished_at.present? %></td>　<!-- .floor_to(15.minutes)(15.minutes)15分刻みで切り捨て-->
          <td>
            <% if day.worked_on == Date.today && day.started_at.present? && day.finished_at.nil? %>
              <%= button_to "退社", user_attendances_path(@user), class: "btn btn-xs btn-primary" %>
            <% end %>
          </td>
          <td>
            <% if day.started_at.present? && day.finished_at.present? %>
              <%= working_times(day.started_at.floor_to(15.minutes), day.finished_at.floor_to(15.minutes),day.nextday) %>
              <% seconds = (day.finished_at - day.started_at).to_i %>
              <% @total_seconds = @total_seconds.to_i + seconds %>
            <% end %>
          </td>
          <td><%= day.note %></td>
          <td><%= day.overwork_finish.to_s(:hour) if day.overwork_finish.present? %></td>
          <td><%= day.overwork_finish.to_s(:min) if day.overwork_finish.present? %></td>
          <td><%= overwork_calculation(day) if day.overwork_finish.present? %></td>
          <td><%= day.overwork_note %></td>
          <td>
            <% unless day.work_request_permit.blank? %>
            <%= "残業申請：#{u_name(day.overwork_superior)}：#{day.work_request_permit}" %>
          <% end %>
          <% unless day.edit_request_permit.blank? %>
            <%= day.work_request_permit.blank? ? "" : tag.br %>
            <%= "勤怠編集：#{u_name(day.conf_change)}：#{day.edit_request_permit}" %>
          <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
    
    <tfoot>
      <tr>
        <td colspan = "2"><%= format_basic_work_time(@user.basic_work_time).to_f * @worked_sum %></td>
        <td colspan = "6"></td>
        <td><%= working_times_sum(@total_seconds) unless @total_seconds.nil? %></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td>
          <% @monthrequest.each do |m| %>
          勤怠申請：<%= u_name(m.boss_id) %>：<%= m.month_approval.nil? ? '未' : m.month_approval %>
          <% end %>
          <%= form_with model: Monthrequest.new, id: "my_form" do |f| %>
            <%= f.select :boss_id, @all_user.map{|t| [t.name, t.id]}, {include_blank: true}, class: "form-control validate[required]" ,id: "boss_select" %>
            <%= f.hidden_field :req_date, value: @first_day %>
            <%= f.hidden_field :user_id, value: @user.id %>
            <%= f.submit "申請", class: "btn btn-primary btn-block" %>
          <% end %>
        </td>
      </tr>
    </tfoot>
    
  </table>
</div>

<div id="user-modal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
<script>
  $(document).ready(function(){
      $("#my_form").validationEngine('attach', {
    promptPosition:"bottomLeft"
  });
  });
</script>