config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get  '/signup',   to: 'users#new'
  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  # get '/edit-basic-info/:id', to: 'users#edit_basic_info', as: :basic_info  勤怠Aでは使わない
  # patch 'update-basic-info',  to: 'users#update_basic_info'  勤怠Aでは使わない
  
  #勤怠編集画面
  get 'users/:id/attendances/:date/edit', to: 'attendances#edit', as: :edit_attendances
  patch 'users/:id/attendances/:date/update', to: 'attendances#update', as: :update_attendances
  
  #残業申請
  post '/overwork_request/:id', to: 'users#overwork_request', as: :overwork_request
  patch '/users/:id/attendances/:attendance_id/update_overwork_request',  to: 'attendances#update_overwork_request', as: :update_overwork_request
  
  #残業申請受け取り、承認
  post '/overwork_permit/:id', to: 'users#overwork_permit', as: :overwork_permit_modal
  patch '/users/:id/attendances/overwork_permit', to: 'attendances#overwork_permit', as: :overwork_permit
  
  #１ヶ月分の勤怠申請、承認
  post '/month_request_modal/:id', to: 'users#month_request_modal', as: :month_request_modal
  patch '/users/:id/attendances/month_request', to: 'attendances#month_request', as: :month_request
  get  'confirmation/:id/:date', to: 'users#confirmation', as: :confirmation
  
   # 勤怠変更申請、承認
  post '/edit_request/:id/:date', to: 'users#edit_request', as: :edit_request_modal
  patch '/users/:id/attendances/edit_request', to: 'attendances#edit_request', as: :edit_request
  
  #勤怠ログ
  get '/change_log/:id', to: 'attendances#change_log', as: :change_log
  
  get '/worktime_logs/search', to: 'attendances#worktime_logs'
  
  #CSV出力
  post '/csv_dl/:id', to: 'users#csv_dl', as: :csv_dl
  post '/csv_import', to: 'users#csv_import', as: :csv_import
  
  
  
  #出勤中社員
  get 'working_now',  to: 'users#working_now', as: :working_now
  
  resources :users do
    collection { post :import }
  resources :attendances, only: :create
  end
  
  resources :basepoints do
    member do
      get 'edit_base'
      patch 'update_base'
    end
  end
  
  resources :monthrequests,  only: [:create]
  
end

app/models/basepoint.rb
class Basepoint < ApplicationRecord
    
    validates :name, presence: true
    validates :number, presence: true
    validates :attendtype, presence: true
end

app/controllers/basepoints_controller.rb
class BasepointsController < ApplicationController
  
  before_action :logged_in_user
  before_action :admin_user
  
  def index
    @basepoints = Basepoint.all
  end

  def new
    @basepoint = Basepoint.new # ベースポイントオブジェクトを生成し、インスタンス変数に代入します。
  end
  
  def create
    @basepoint = Basepoint.new(basepoint_params)
    if @basepoint.save
      flash[:success] = '拠点情報を追加しました。'
      redirect_to basepoints_path
    else
      render :new
    end
  end
  
  def destroy
    Basepoint.find(params[:id]).destroy
    flash[:success] = "削除しました。"
    redirect_to basepoints_path
  end
  
  def edit_base
    @basepoint = Basepoint.find(params[:id])
  end
  
  def update
   @basepoint = Basepoint.find(params[:id])
   if @basepoint.update_attributes(basepoint_params)
    flash[:success] = "拠点情報を更新しました。"
    redirect_to basepoints_path  
   else
    render 'edit_base'
   end
  end
  
  
  
  private

    def basepoint_params
      params.require(:basepoint).permit(:name, :number, :attendtype)
    end

    # beforeアクション

    # ログイン済みユーザーか確認
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "ログインしてください。"
        redirect_to login_url
      end
    end
    
     # 正しいユーザーかどうか確認
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user) or current_user.admin?
    end
    
    
    # 管理者かどうか確認
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/basepoints_helper.rb
module BasepointsHelper
end

app/views/basepoints/edit_base.html.erb
<% provide(:title, '拠点追加') %>
<h1>拠点情報編集</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @basepoint, local: true) do |f| %>
    <%= render 'shared/error_messages_basepoint', object: @basepoint %>
   
    
      <%= f.label :拠点名 %>
      <%= f.text_field :name %>

      <%= f.label :番号 %>
      <%= f.number_field :number %>
      
      <%= f.label :勤怠種類 %>
      <%= f.text_field :attendtype %>

      <%= f.submit "送信", class: "btn btn-primary btn-block btn-signup" %>
    <% end %>
  </div>
</div>

app/views/basepoints/edit_basic_info.html.erb
<% provide(:title, '拠点追加') %>
<h1>拠点情報編集</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @basepoint, local: true) do |f| %>
   
    
      <%= f.label :拠点名 %>
      <%= f.text_field :name %>

      <%= f.label :番号 %>
      <%= f.number_field :number %>
      
      <%= f.label :勤怠種類 %>
      <%= f.text_field :attendtype %>

      <%= f.submit "送信", class: "btn btn-primary btn-block btn-signup" %>
    <% end %>
  </div>
</div>

app/views/basepoints/index.html.erb
<% provide(:title, '拠点一覧') %>
<h1>拠点一覧</h1>

<table class = "table-bordered  table-condensed table-striped basepoints">
 
    <thead>
      <tr> <!--rowspan:縦結合、colspan：横結合-->
        <th></th>
        <th></th>
        <th>拠点名</th>
        <th>拠点番号</th>
        <th>勤怠種類</th>
      </tr>
      <% @basepoints.each do |basepoint| %>
      <tr> <!--rowspan:縦結合、colspan：横結合-->
        <th><%= link_to "拠点情報編集", edit_base_basepoint_path(basepoint),class: "btn btn-primary" %></th>
        <th><%= link_to "削除", basepoint, method: :delete, data: { confirm: "削除してよろしいですか？" },class: "btn btn-primary" %></th>
        <th><%= basepoint.name %></th>
        <th><%= basepoint.number %></th>
        <th><%= basepoint.attendtype %></th>
      </tr>
    </thead>
<% end %>
</table>
<%= link_to "拠点情報追加",new_basepoint_path, class: "btn btn-primary" %>

app/views/basepoints/new.html.erb
<% provide(:title, '拠点追加') %>
<h1>拠点追加</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @basepoint, local: true) do |f| %>
    <%= render 'shared/error_messages_basepoint' %>
    
      <%= f.label :拠点名 %>
      <%= f.text_field :name %>

      <%= f.label :番号 %>
      <%= f.number_field :number %>
      
      <%= f.label :勤怠種類 %>
      <%= f.text_field :attendtype %>

      <%= f.submit "追加", class: "btn btn-primary btn-block btn-signup" %>
    <% end %>
  </div>
</div>