config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get  '/signup',   to: 'users#new'
  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  # get '/edit-basic-info/:id', to: 'users#edit_basic_info', as: :basic_info  勤怠Aでは使わない
  # patch 'update-basic-info',  to: 'users#update_basic_info'  勤怠Aでは使わない
  
  #勤怠編集画面
  get 'users/:id/attendances/:date/edit', to: 'attendances#edit', as: :edit_attendances
  patch 'users/:id/attendances/:date/update', to: 'attendances#update', as: :update_attendances
  
  #残業申請
  post '/overwork_request/:id', to: 'users#overwork_request', as: :overwork_request
  patch '/users/:id/attendances/:attendance_id/update_overwork_request',  to: 'attendances#update_overwork_request', as: :update_overwork_request
  
  #残業申請受け取り、承認
  post '/overwork_permit/:id', to: 'users#overwork_permit', as: :overwork_permit_modal
  patch '/users/:id/attendances/overwork_permit', to: 'attendances#overwork_permit', as: :overwork_permit
  
  #１ヶ月分の勤怠申請、承認
  post '/month_request_modal/:id', to: 'users#month_request_modal', as: :month_request_modal
  patch '/users/:id/attendances/month_request', to: 'attendances#month_request', as: :month_request
  get  'confirmation/:id/:date', to: 'users#confirmation', as: :confirmation
  
   # 勤怠変更申請、承認
  post '/edit_request/:id/:date', to: 'users#edit_request', as: :edit_request_modal
  patch '/users/:id/attendances/edit_request', to: 'attendances#edit_request', as: :edit_request
  
  #勤怠ログ
  get '/change_log/:id', to: 'attendances#change_log', as: :change_log
  
  get '/worktime_logs/search', to: 'attendances#worktime_logs'
  
  #CSV出力
  post '/csv_dl/:id', to: 'users#csv_dl', as: :csv_dl
  post '/csv_import', to: 'users#csv_import', as: :csv_import
  
  
  
  #出勤中社員
  get 'working_now',  to: 'users#working_now', as: :working_now
  
  resources :users do
    collection { post :import }
  resources :attendances, only: :create
  end
  
  resources :basepoints do
    member do
      get 'edit_base'
      patch 'update_base'
    end
  end
  
  resources :monthrequests,  only: [:create]
  
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user
  validates :worked_on, presence: true
  
  
  validate :finished_at_edit_valid
   def finished_at_edit_valid
    if started_at.nil? && finished_at.present?
     errors.add(:finished_at, "出社時間が入力されていません。")
    end
   end
   
  validate :finished_at_cannot_be_faster_than_started_at
  def finished_at_cannot_be_faster_than_started_at
    if   started_at.present? && finished_at.present?
    if   started_at > finished_at
        errors.add(:finished_at, "退勤時間が出勤時間より早くなっています。")
    end
    end
  end
end

app/helpers/attendances_helper.rb
module AttendancesHelper
  def current_time
    Time.new(
        # Time.now.year,
        # Time.now.month,
        # Time.now.day,
        2000,1,1,
        Time.now.hour,
        Time.now.min,0
        )
  end
  
  def working_times(started_at, finished_at, nextday)
    # 時間のみ正しいので
    started_at = started_at - started_at.beginning_of_day
    finished_at = finished_at - finished_at.beginning_of_day
    if nextday
      format("%.2f", (((finished_at - started_at + 86400) / 60) / 60.0))
    else
      format("%.2f", (((finished_at - started_at) / 60) / 60.0))
    end
  end
  # 合計時間計算用
  def totalseconds(started_at, finished_at, nextday)
    @total_seconds ||= 0
    seconds = (finished_at - finished_at.beginning_of_day) - (started_at - started_at.beginning_of_day)
    seconds += 86400 if nextday
    @total_seconds += seconds
  end
  
  def working_times_sum(seconds)
    format("%.2f", seconds / 60 / 60.0)
  end
  
  # 不正な値はfalse返す
  def date_valid?(date)
    !!date.to_date rescue false
  end
  
  def first_day(date)
    !date.nil? ? Date.parse(date).beginning_of_month : Date.current.beginning_of_month
  end
  
  # 勤怠表示用データ取得
  def user_attendances_month_date
    @user.attendances.where('worked_on >= ? and worked_on <= ?', @first_day, @last_day).order('worked_on')
  end
  
  # 勤怠編集画面の値が正しいか
  def attendances_invalid? #attendancesでバリデーションが通ればfalse、引っかかればtrue
    # conf_changeに何か入っている場合のみチェック
    attendances = true
    attendances_params.each do |id, item|
      
      if !item[:started_at].blank? && !item[:finished_at].blank? || !item[:started_at].blank? && item[:finished_at].blank? || item[:started_at].blank? && !item[:finished_at].blank? #
          if item[:conf_change].blank?
            attendances = false
                break
          end
      end
      
      if !item[:conf_change].blank? #conf_change入ってる
        if (!item[:started_at].blank? && item[:finished_at].blank?) || (item[:started_at].blank? && !item[:finished_at].blank?)
          attendances = false
          break
        end
        
        item[:nextday] = item[:nextday] == "true" ? true : false # 文字列で入ってくるので変換
        
        if item[:started_at] > item[:finished_at] && item[:nextday] == false
          attendances = false
          break
        end
          
        if !item[:started_at].blank? && !item[:finished_at].blank? # form start fin入ってる
          if item[:conf_change].blank? # 上長入ってない
            data = Attendance.find(id)
            # 変更したことなくて(edit_request_permitがなくて)ボタンで出勤退勤登録していたら
            if !data.origin_start.nil? && !data.origin_fin.nil? && data.edit_request_permit.blank?
              
              # 以下は変更されていたらfalse
              bool_s = (data.started_at - data.started_at.beginning_of_day) == ((Time.parse(item[:started_at]) - Time.parse(item[:started_at]).beginning_of_day))    
              bool_e = (data.finished_at - data.finished_at.beginning_of_day) == ((Time.parse(item[:finished_at]) - Time.parse(item[:finished_at]).beginning_of_day))
        
              item[:conf_change] = item[:conf_change].blank? ? nil : item[:conf_change].to_i
              bool_next = data.nextday == item[:nextday]
              bool_boss = data.conf_change == item[:conf_change]
              # form DBデータ一致
              if bool_s && bool_e && bool_next && bool_boss
                next
              else
                # 既存のデータを修正するので上長必要
                attendances = false
                break
              end
            end
        
            if !data.started_at.blank? || !data.finished_at.blank? # DB start fin どちらか入っている(ボタンによるもの、編集したパターンあり)
              # 既存のデータを修正するので上長必要
              attendances = false
              break
            elsif data.edit_request_permit.blank? # 一度変更したら「申請中、承認」入る →1.編集画面で無から登録 2.出勤・退勤ボタンから登録
              attendances = false
              break
            elsif !data.edit_request_permit.blank? # 2回目以降の登録
              attendances = false
              break
            end
          else # 上長入っている
            next
          end
        elsif item[:started_at].blank? && item[:finished_at].blank? # form start finカラ
          if item[:conf_change].blank? # 上長カラ
            next
          else
            # 出勤・退勤がカラで上長が登録されなかった場合
            attendances = false
            break
          end
        end
      end
    end
    attendances
  end
  
  def ge_today?(day)
    day.worked_on <= Date.current
  end
  
  def future_month?(firstday)
    @first_day > Date.today.beginning_of_month
  end
end

# 各ユーザー残業申請モーダルからの値判定
def work_request_invalid?
  attendances = true
  item = work_request_params
  if item[:overwork_finish].blank? || item[:overwork_note].blank? || item[:overwork_superior].blank?
    attendances = false
  end
  attendances
end

# モーダル予定外時間を計算
def overwork_calculation(day)
  work_end_sec = (day.overwork_finish - day.overwork_finish.beginning_of_day) - (@user.designated_work_end_time - @user.designated_work_end_time.beginning_of_day)
  # 翌日で申請している場合は24時間(86400sec)足す
  over_time = day.next_day == 'false' ? work_end_sec : work_end_sec + 86400
  over_time = format("%.2f", over_time / 60 / 60.0)
  over_time
end

app/views/attendances/change_log.html.erb
<% provide(:title,"勤怠ログ" ) %>
<div>
  <h1>勤怠ログ</h1>
<div class="col-xs-3">
<button type="button" class="btn btn-default" id="reset">リセット</button>

    <form role="form">
        <div class="input-group" id="year">
            <div class="input-group-btn">
                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                  年
                    <span class="caret"></span>
                </button>
                <ul id="color-dropdown-menu" class="dropdown-menu" role="menu">
                  <% (@from_year..@to_year).each do |y| %>
                    <%= content_tag(:li, class: "input", id: y) do %>
                      <% concat content_tag(:a, y) %>
                    <% end %>
                  <% end %>
                </ul>
            </div>
            <%= text_field_tag 'sel_month', @sel_today.strftime("%-Y"), class: "form-control", readonly: "" %>
        </div>
    </form>
    <form role="form">
        <div class="input-group" id="month">
            <div class="input-group-btn">
                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                  月
                    <span class="caret"></span>
                </button>
                <ul id="color-dropdown-menu" class="dropdown-menu" role="menu">
                  <% (1..12).each do |m| %>
                    <%= content_tag(:li, class: "input", id: m) do %>
                      <% concat content_tag(:a, m) %>
                    <% end %>
                  <% end %>
                </ul>
            </div>
          <%= text_field_tag 'sel_month', @sel_today.strftime("%-m"), class: "form-control", readonly: "" %>
        </div>
    </form>
</div>
    <table class = "table-bordered table-striped table-condensed">
        <thead>
          <tr>
            <th>日付</th>
            <th>変更前出社時間</th>
            <th>変更前退社時間</th>
            <th>変更後出社時間</th>
            <th>変更後退社時間</th>
            <th>提出者</th>
            <th>承認日</th>
          </tr>
        <thead>
    <tbody class="attendance_table">
      <% @log_lists.each do |log_list| %>
        <tr>
          <td><%= log_list.worked_on.nil?    ? nil : log_list.worked_on.strftime("%Y-%m-%d") %></td>
          <td><%= log_list.origin_start.nil? ? nil : log_list.origin_start.strftime("%H:%M") %></td>
          <td><%= log_list.origin_fin.nil?   ? nil : log_list.origin_fin.strftime("%H:%M")%></td>
          <td><%= log_list.started_at.nil?   ? nil : log_list.started_at.strftime("%H:%M") %></td>
          <td><%= log_list.finished_at.nil?  ? nil : log_list.finished_at.strftime("%H:%M") %></td>
          <td><%= User.find(log_list.conf_change).name unless log_list.conf_change.blank? %></td>
          <td><%= log_list.permitdate %></td>
        </tr>
      <% end %>
    </tbody>
    </table>
</div>

<script>
  $(function(){
    var d = new Date();
    year = d.getFullYear();
    month = d.getMonth()+1;
    
    $("#month li").click(function () {
      // year = $("#year li").attr('id')
      month = $(this).attr('id')
      $("#month input").val(month);
      
      $.ajax({
        url: '/worktime_logs/search',
        type: 'GET',
        data: {
        year: year,
        month: month
        }, 
        dataType: 'json'
      })
      .done(function(data){ 
        console.log("読み込みに成功しました");
        
        $('tbody').find('tr').remove(); 
        $('tbody').find('td').remove();
      
        function tern_into_time(t) {
          if(!!t){
            let d = new Date(t);
            // DB登録されてる値がUTC
            let hour = d.getHours() + 9 >= 24 ?  ("0"+(d.getHours() - 15)).slice(-2) : ("0"+(d.getHours() + 9)).slice(-2);
            return `${hour}:${("0"+(d.getMinutes())).slice(-2)}`; 
            } else {
            return '';
          }
        }
    
        function isNullOrUndefined(obj){
          return obj === undefined || obj === null ? '' : obj;
        }
        
        function DateisNullOrUndefined(t){
          if(!!t){
            let d = new Date(t);
            return `${d.getFullYear()}-${('0'+ (d.getMonth()+1)).slice(-2)}-${('0'+ d.getDate()).slice(-2)}`; 
          } else {
            return '';
          }
        }
        $(data).each(function(i, val){
         if(!!val.started_at && !!val.finished_at) {
          $('tbody').append(
            $('<tr>')
            .append('<td>' + val.worked_on + '</td>')
            .append('<td>' + tern_into_time(val.origin_start) + '</td>')
            .append('<td>' + tern_into_time(val.origin_fin) + '</td>')
            .append('<td>' + tern_into_time(val.started_at) + '</td>')
            .append('<td>' + tern_into_time(val.finished_at) + '</td>')
            .append('<td>' + isNullOrUndefined(val.name) + '</td>')
            .append('<td>' + DateisNullOrUndefined(val.permitdate) + '</td>')
            .append('</tr>')
            )
          }
          else{
            // 処理を飛ばす ... continue
            return true;
          }
        });
      }).fail(function(result) {
      console.log("失敗");
      });
    });
  	$("#year li").click(function () {
      	year = $(this).attr('id')
      	$("#year input").val(year);
      	$.ajax({
        url: '/worktime_logs/search',
        type: 'GET',
        data: {
            year: year,
            month: month
        }, 
        dataType: 'json'
    })
    	.done(function(data){ 
    		console.log("読み込みに成功しました");

    		
    		$('tbody').find('tr').remove(); 
    		$('tbody').find('td').remove();
    		
  		  function tern_into_time(t) {
    		  if(!!t){
    		    let d = new Date(t);
    		    // DB登録されてる値がUTC。修正予定
    		    let hour = d.getHours() + 9 >= 24 ?  ("0"+(d.getHours() - 15)).slice(-2) : ("0"+(d.getHours() + 9)).slice(-2);
    		    return `${hour}:${("0"+(d.getMinutes())).slice(-2)}`; 
    		  } else {
    		    return '';
    		  }
  		  }
  		  
  		  function isNullOrUndefined(obj){
  		    return obj === undefined || obj === null ? '' : obj;
        }
        
        function DateisNullOrUndefined(t){
  		    if(!!t){
    		    let d = new Date(t);
            return `${d.getFullYear()}-${('0'+ (d.getMonth()+1)).slice(-2)}-${('0'+ d.getDate()).slice(-2)}`; 
    		  } else {
    		    return '';
    		  }
        }
    		$(data).each(function(i, val){
    		   if(!!val.started_at && !!val.finished_at) {
            $('tbody').append(
    		    $('<tr>')
    		      .append('<td>' + val.worked_on + '</td>')
    		      .append('<td>' + tern_into_time(val.origin_start) + '</td>')
    		      .append('<td>' + tern_into_time(val.origin_fin) + '</td>')
    		      .append('<td>' + tern_into_time(val.started_at) + '</td>')
    		      .append('<td>' + tern_into_time(val.finished_at) + '</td>')
    		      .append('<td>' + isNullOrUndefined(val.name) + '</td>')
    		      .append('<td>' + DateisNullOrUndefined(val.permitdate) + '</td>')
    		      .append('</tr>')
    		    )
            }
            else{
              // 処理を飛ばす ... continue
              return true;
            }
    		});
    		
			}).fail(function(result) {
    console.log("失敗");
    });
  });
  
  $("#reset").click(function () {
    console.log("Reset");
    year = d.getFullYear();
  	month = d.getMonth()+1;
    $("#year input").val(year);
    $("#month input").val(month);
  });
  
});
</script>

app/views/attendances/edit.html.erb
<% provide(:title, "勤怠編集" ) %>
<div>
  <h1>勤怠編集画面</h1>
  <%= form_for(@user, url: update_attendances_path, method: :patch) do |f| %>
    <table class = "table-bordered table-striped table-condensed">
      <thead>
        <tr>
          <th>日付</th>
          <th>曜日</th>
          <th>出勤時間</th>
          <th>退勤時間</th>
          <th>翌日</th>
          <th>在社時間</th>
          <th>備考</th>
          <th>指示者確認</th>
        </tr>
      </thead>
      <tbody>
        <% @dates.each do |day| %>
          <%= fields_for "attendances[]", day do |af| %>
            <tr>
              <td><%= day.worked_on.to_s(:date) %></td>
              <td><%= %w{日 月 火 水 木 金 土}[day.worked_on.wday] %></td>
              <td>
                <% if day.worked_on > Date.today %>
                 <%= af.time_field :started_at, :readonly => true, class: "form-control" if ge_today?(day) %>
                <% else %>
                 <%= af.time_field :started_at, class: "form-control" if ge_today?(day) %>
                <% end %>
              </td>
              <td>
                <% if day.worked_on > Date.today %>
                 <%= af.time_field :finished_at, :readonly => true, class: "form-control" if ge_today?(day) %>
                <% else %>
                 <%= af.time_field :finished_at, class: "form-control" if ge_today?(day) %>
                <% end %>
              </td>
              <td style="width:40px;"><%= af.check_box :nextday,  {}, "true", "false" if ge_today?(day) %></td>
              <td>
                <% if day.started_at.present? && day.finished_at.present? %>
                  <%= working_times(day.started_at, day.finished_at,day.nextday) %>
                <% end %>
              </td>
              <td><%= af.text_field :note, class: "form-control" if ge_today?(day) %></td>
              <td><%= af.select :conf_change, @all_user.map{|t| [t.name, t.id]}, {include_blank: true}, class: "form-control" if ge_today?(day) %></td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
    <div class="btn-attendances-update">
      <%= f.submit "更新", class: "btn btn-primary" %>
      <%= link_to "キャンセル", user_path(@user, params:{first_day: @first_day }), class: "btn btn-default btn-block" %>
    </div>
  <% end %>
</div>