config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get  '/signup',   to: 'users#new'
  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  # get '/edit-basic-info/:id', to: 'users#edit_basic_info', as: :basic_info  勤怠Aでは使わない
  # patch 'update-basic-info',  to: 'users#update_basic_info'  勤怠Aでは使わない
  
  #勤怠編集画面
  get 'users/:id/attendances/:date/edit', to: 'attendances#edit', as: :edit_attendances
  patch 'users/:id/attendances/:date/update', to: 'attendances#update', as: :update_attendances
  
  #残業申請
  post '/overwork_request/:id', to: 'users#overwork_request', as: :overwork_request
  patch '/users/:id/attendances/:attendance_id/update_overwork_request',  to: 'attendances#update_overwork_request', as: :update_overwork_request
  
  #残業申請受け取り、承認
  post '/overwork_permit/:id', to: 'users#overwork_permit', as: :overwork_permit_modal
  patch '/users/:id/attendances/overwork_permit', to: 'attendances#overwork_permit', as: :overwork_permit
  
  #１ヶ月分の勤怠申請、承認
  post '/month_request_modal/:id', to: 'users#month_request_modal', as: :month_request_modal
  patch '/users/:id/attendances/month_request', to: 'attendances#month_request', as: :month_request
  get  'confirmation/:id/:date', to: 'users#confirmation', as: :confirmation
  
   # 勤怠変更申請、承認
  post '/edit_request/:id/:date', to: 'users#edit_request', as: :edit_request_modal
  patch '/users/:id/attendances/edit_request', to: 'attendances#edit_request', as: :edit_request
  
  #勤怠ログ
  get '/change_log/:id', to: 'attendances#change_log', as: :change_log
  
  get '/worktime_logs/search', to: 'attendances#worktime_logs'
  
  #CSV出力
  post '/csv_dl/:id', to: 'users#csv_dl', as: :csv_dl
  post '/csv_import', to: 'users#csv_import', as: :csv_import
  
  
  
  #出勤中社員
  get 'working_now',  to: 'users#working_now', as: :working_now
  
  resources :users do
    collection { post :import }
  resources :attendances, only: :create
  end
  
  resources :basepoints do
    member do
      get 'edit_base'
      patch 'update_base'
    end
  end
  
  resources :monthrequests,  only: [:create]
  
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <% if logged_in? %>
    <%= link_to "勤怠システム",current_user, id: "logo" %>
    <% else %>
    <%= link_to "勤怠システム", root_path, id: "logo" %>
    <% end %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>　<!-- もしログインしていれば下記の処理が行われる -->
        <% if current_user.try(:admin?) %> <!--管理者権限があるユーザーのみに"ユーザー一覧"が表示される-->
          <li><%= link_to "トップへ", root_path %></li>
          <li><%= link_to "基本情報の修正" ,'#'%></li> <!--(current_user)を入れることで現在ログイン中のユーザーの情報を編集できる-->
          <li><%= link_to "ユーザ一覧", users_path %></li>
          <li><%= link_to "出勤社員一覧", working_now_path %></li>
          <li><%= link_to "拠点情報の修正",basepoints_path %></li>
        <% else %>
          <li><%= link_to "トップへ", current_user %></li>
          <% end %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              アカウント<b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <% if current_user.try(:admin?) %>
              <li><li><%= link_to "設定", edit_user_path(current_user) %></li>
              <% else %>
              <li><%= link_to "勤怠情報表示", current_user %></li>
              <li><%= link_to "設定", edit_user_path(current_user) %></li>
              <% end %>
              <li class="divider"></li>
              <li>
                <%= link_to "ログアウト", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "トップへ", root_path %></li>
          <li><%= link_to "ログイン", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                               'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application',
                               'data-turbolinks-track': 'reload' %>
                               
  <%= render 'layouts/shim' %>
  </head>
  <body>
  <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>